# Generated by GitHub Copilot - Sep-19-2026
"""Streamlit dashboard for screening candidates and scheduling interview invitations."""

from __future__ import annotations

import uuid
from datetime import datetime
from io import BytesIO

import streamlit as st
from langgraph.types import Command
from docx import Document
from pypdf import PdfReader

from graphs.parent_graph import parent_graph
from agents.reply_scheduler import send_calendar_invite


MAX_JOB_DESCRIPTION_BYTES = 2 * 1024 * 1024


def read_job_description(uploaded_file: st.runtime.uploaded_file_manager.UploadedFile) -> str:
    """Return validated job-description text from an uploaded document or text file."""
    file_bytes = uploaded_file.getvalue()
    if len(file_bytes) > MAX_JOB_DESCRIPTION_BYTES:
        raise ValueError("The job description must be 2 MB or smaller.")

    if uploaded_file.name.lower().endswith(".pdf"):
        reader = PdfReader(BytesIO(file_bytes))
        return "\n".join(page.extract_text() or "" for page in reader.pages).strip()

    if uploaded_file.name.lower().endswith(".docx"):
        document = Document(BytesIO(file_bytes))
        return "\n".join(paragraph.text for paragraph in document.paragraphs).strip()

    return file_bytes.decode("utf-8").strip()


def initial_pipeline_state(job_description: str) -> dict:
    """Build the initial state required by the existing parent interview graph."""
    return {
        "resume_paths": [
            "resumes/Kavinsharaj_GenAI_Engineer.pdf",
            "resumes/priya_sharma_resume.pdf",
            "resumes/arjun_mehta_resume.pdf",
        ],
        "job_description": job_description,
        "ranked_candidates": [],
        "approved_candidates": [],
        "child_thread_ids": {},
        "scheduled_meetings": [],
        "processed_reply_keys": [],
        "error": None,
    }


def screen_candidates(job_description: str) -> tuple[str, list[dict]]:
    """Run screening until the graph pauses for the recruiter's approval decision."""
    thread_id = str(uuid.uuid4())
    config = {"configurable": {"thread_id": thread_id}}
    ranked_candidates: list[dict] = []

    for event in parent_graph.stream(initial_pipeline_state(job_description), config=config):
        node_output = event.get("screen_resumes")
        if node_output:
            if node_output.get("error"):
                raise RuntimeError(node_output["error"])
            ranked_candidates = node_output.get("ranked_candidates", [])

    if not ranked_candidates:
        raise RuntimeError("The screener did not return any candidates.")
    return thread_id, ranked_candidates


def request_candidate_availability(thread_id: str, candidate_emails: list[str]) -> dict:
    """Resume the paused graph and email every HR-selected candidate for availability."""
    config = {"configurable": {"thread_id": thread_id}}
    child_thread_ids: dict[str, str] = {}

    for event in parent_graph.stream(
        Command(resume={"approved": candidate_emails}), config=config
    ):
        node_output = event.get("spawn_children")
        if node_output:
            child_thread_ids = node_output.get("child_thread_ids", {})

    sent_emails = {email.lower() for email in child_thread_ids}
    missing_emails = [email for email in candidate_emails if email.lower() not in sent_emails]
    if missing_emails:
        raise RuntimeError(
            f"Availability requests were not sent to: {', '.join(missing_emails)}. "
            "Check the email configuration and try again."
        )
    return child_thread_ids


def check_candidate_replies(thread_id: str) -> list[dict]:
    """Poll the approved candidate mailbox replies and return extracted availability."""
    config = {"configurable": {"thread_id": thread_id}}
    outcomes: list[dict] = []

    for event in parent_graph.stream(Command(goto="monitor_replies"), config=config):
        node_output = event.get("monitor_replies")
        if node_output:
            if node_output.get("error"):
                raise RuntimeError(node_output["error"])
            outcomes = node_output.get("scheduled_meetings", [])
    return outcomes


def send_confirmed_invite(candidate: dict, selected_time: str, meeting_url: str) -> dict:
    """Send a calendar invitation only after HR explicitly selects an available time."""
    start_at = datetime.fromisoformat(selected_time)
    return send_calendar_invite(candidate["name"], candidate["email"], start_at, meeting_url)


def reset_run() -> None:
    """Clear the active graph run and candidate data from this browser session."""
    for key in (
        "thread_id", "ranked_candidates", "scheduled_candidates", "reply_outcomes",
        "confirmed_invitation",
    ):
        st.session_state.pop(key, None)


def render_candidate_details(candidate: dict) -> None:
    """Render the selected candidate's screening result and available reply information."""
    st.subheader(candidate["name"])
    st.caption(candidate["email"])
    st.metric("Match score", f"{candidate['score']:.0%}")
    st.markdown("**Screening response**")
    st.write(candidate["rationale"])

    reply_outcomes = st.session_state.get("reply_outcomes", [])
    candidate_replies = [
        outcome
        for outcome in reply_outcomes
        if outcome.get("candidate_email", "").lower() == candidate["email"].lower()
    ]
    availability = next(
        (
            outcome.get("available_times", [])
            for outcome in candidate_replies
            if outcome.get("status") == "availability_found"
        ),
        [],
    )
    if availability:
        st.markdown("**Available times**")
        selected_time = st.radio(
            "Choose an interview time", availability, format_func=lambda value: datetime.fromisoformat(value).strftime("%a, %d %b %Y at %I:%M %p %Z")
        )
        meeting_url = st.text_input(
            "Meeting link", placeholder="https://teams.microsoft.com/l/meetup-join/..."
        )
        if st.button("Send calendar invite", type="primary", use_container_width=True):
            try:
                with st.spinner("Sending calendar invite..."):
                    st.session_state.confirmed_invitation = send_confirmed_invite(
                        candidate, selected_time, meeting_url
                    )
                st.rerun()
            except (RuntimeError, ValueError) as error:
                st.error(f"Unable to send the calendar invite: {error}")
    elif candidate_replies:
        st.markdown("**Interview response**")
        st.info("No clear future availability was found. Review the candidate's email manually.")
    if st.session_state.get("confirmed_invitation", {}).get("candidate_email") == candidate["email"]:
        st.success("Calendar invite sent.")
    elif candidate["email"] in st.session_state.get("scheduled_candidates", []):
        st.info("Availability request sent. Use Check availability once the candidate responds.")


def render_dashboard() -> None:
    """Render the recruiter workflow and dispatch actions to the interview graph."""
    st.set_page_config(page_title="Interview Agent", page_icon="IA", layout="wide")
    st.title("Interview Agent")
    st.caption("Screen resumes, review fit, and send a personalized interview invitation.")

    with st.sidebar:
        st.header("Job description")
        uploaded_file = st.file_uploader(
            "Upload PDF, Word, TXT, or Markdown", type=["pdf", "docx", "txt", "md"]
        )
        job_description = st.text_area("Or paste the job description", height=220)
        start_disabled = uploaded_file is None and not job_description.strip()
        if st.button("Rank candidates", type="primary", disabled=start_disabled, use_container_width=True):
            try:
                source_text = read_job_description(uploaded_file) if uploaded_file else job_description.strip()
                if not source_text:
                    raise ValueError("The job description is empty.")
                with st.spinner("Screening resumes..."):
                    thread_id, ranked_candidates = screen_candidates(source_text)
                st.session_state.thread_id = thread_id
                st.session_state.ranked_candidates = ranked_candidates
                st.session_state.pop("scheduled_candidates", None)
                st.session_state.pop("reply_outcomes", None)
            except (OSError, RuntimeError, UnicodeDecodeError, ValueError) as error:
                st.error(f"Unable to screen candidates: {error}")

        if st.session_state.get("thread_id"):
            st.button("Start new run", on_click=reset_run, use_container_width=True)

    candidates = st.session_state.get("ranked_candidates", [])
    if not candidates:
        st.info("Upload or paste a job description to rank the resumes in the configured resume folder.")
        return

    left_column, right_column = st.columns([1.2, 1])
    with left_column:
        st.subheader("Ranked candidates")
        candidate_by_email = {candidate["email"]: candidate for candidate in candidates}
        selected_emails = st.multiselect(
            "Candidates to contact",
            options=list(candidate_by_email),
            format_func=lambda email: (
                f"{candidate_by_email[email]['name']} - {candidate_by_email[email]['score']:.0%}"
            ),
        )
        candidate_labels = {
            f"{index + 1}. {candidate['name']} - {candidate['score']:.0%}": candidate
            for index, candidate in enumerate(candidates)
        }
        selected_label = st.radio("Review candidate", candidate_labels, label_visibility="collapsed")
        selected_candidate = candidate_labels[selected_label]

    with right_column:
        render_candidate_details(selected_candidate)
        scheduled_candidates = st.session_state.get("scheduled_candidates", [])
        if scheduled_candidates:
            st.success(f"Availability request sent to {len(scheduled_candidates)} candidate(s).")
        elif st.button(
            "Request availability",
            type="primary",
            disabled=not selected_emails,
            use_container_width=True,
        ):
            try:
                with st.spinner("Sending availability request..."):
                    request_candidate_availability(st.session_state.thread_id, selected_emails)
                st.session_state.scheduled_candidates = selected_emails
                st.rerun()
            except RuntimeError as error:
                st.error(str(error))

        if scheduled_candidates:
            if st.button("Check availability", use_container_width=True):
                try:
                    with st.spinner("Reading the latest candidate reply..."):
                        st.session_state.reply_outcomes = check_candidate_replies(st.session_state.thread_id)
                    st.rerun()
                except RuntimeError as error:
                    st.error(f"Unable to check replies: {error}")


if __name__ == "__main__":
    render_dashboard()
