# agents/email_composer.py
import json

from llm import client
from state import ChildState

SYSTEM_PROMPT = """You are a professional recruiter writing an interview invitation email.

You will receive one candidate's details and a job description.
Write a personalized interview invitation email for that candidate.
Personalization means referencing something specific from their resume.

Return ONLY a JSON object in this exact format, no other text:
{
  "to": "candidate@email.com",
  "subject": "Interview Invitation — [Role Name]",
  "body": "Full email body here"
}

Rules:
- Keep email under 150 words
- Ask candidate to reply with 3 available time slots
- Be warm but professional
- Sign off as: The Hiring Team
"""


def email_composer_node(state: ChildState) -> dict:   # ← ChildState
    """
    Handles ONE candidate.
    Reads candidate_name, candidate_email, candidate_resume, job_description.
    Writes email_draft to state.
    """

    # Generated by GitHub Copilot - Sep-16-2026
    response = client.responses.create(
        model="openai/gpt-oss-20b",
        input=[
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": f"""Job Description:
{state['job_description']}

Candidate:
  Name  : {state['candidate_name']}
  Email : {state['candidate_email']}
  Resume: {state['candidate_resume'][:1500]}

Draft a personalized invitation email for this candidate."""},
        ],
    )
    last_message = response.output_text

    clean = last_message.strip()
    if clean.startswith("```"):
        clean = clean.split("```")[1]
        clean = clean.removeprefix("json").strip()

    try:
        draft = json.loads(clean)
        return {"email_draft": draft}
    except (json.JSONDecodeError, KeyError) as e:
        return {"error": f"EmailComposer failed: {e}\nRaw: {last_message}"}
