import json
import re

from langchain.agents import create_agent
from langchain_openai import ChatOpenAI

from llm import client
from state import CandidateScore, InterviewState
from tools.pdf_reader import extract_pdf_text

SYSTEM_PROMPT = """You are a technical recruiter assistant.

You will receive:
1. A job description
2. A list of resume file paths

Your job:
- Call the extract_pdf_text tool once per resume file path
- Read the extracted text carefully
- Score each candidate from 0.0 to 1.0 against the job description
- Extract the candidate's email address from their resume text

Return ONLY a JSON object in this exact format, no other text:
{
  "ranked_candidates": [
    {
      "name": "Full Name",
      "email": "email@example.com",
      "score": 0.87,
    "rationale": "One sentence explaining the score"
    }
  ]
}

Rules:
- Sort by score descending (highest first)
- If you cannot find an email in a resume, set email to "NOT_FOUND"
- Score honestly — a 0.5 means genuinely average fit, not a fallback
- - rationale must be a single sentence, maximum 20 words, citing one specific skill or achievement
- Do not include resume text in the response
"""


# Generated by GitHub Copilot - Sep-16-2026
screener_model = ChatOpenAI(
    model="openai/gpt-oss-20b",
    api_key=client.api_key,
    base_url=str(client.base_url),
)

screener_agent = create_agent(
    model=screener_model,
    tools=[extract_pdf_text],
    system_prompt=SYSTEM_PROMPT,
)


def resume_screener_node(state: InterviewState) -> dict:
    """
    LangGraph node. Reads resume_paths + job_description from state,
    runs the screener agent, writes ranked_candidates back to state.
    """

    # ── build the user message ─────────────────────────────────────────
    resume_list = "\n".join(
        f"- {path}" for path in state["resume_paths"]
    )
    user_message = f"""Job Description:
{state['job_description']}

Resume file paths to evaluate:
{resume_list}

Please extract and score all resumes now."""

    # ── run the agent ──────────────────────────────────────────────────
    result = screener_agent.invoke({
        "messages": [{"role": "user", "content": user_message}]
    })

    # ── parse the output ───────────────────────────────────────────────
    # LangGraph can finish with an empty tool/status message, so find the
    # most recent model response that actually contains JSON content.
    last_message = next(
        (
            message.content
            for message in reversed(result["messages"])
            if isinstance(message.content, str) and message.content.strip()
        ),
        "",
    )

    try:
        if not last_message:
            raise ValueError("The screening model returned an empty response.")
        data = json.loads(last_message.strip().removeprefix("```json").removesuffix("```").strip())
        ranked: list[CandidateScore] = data["ranked_candidates"]

        # Generated by GitHub Copilot - Sep-16-2026
        resume_text_by_email = {}
        for resume_path in state["resume_paths"]:
            resume_text = extract_pdf_text.invoke({"file_path": resume_path})
            for email in re.findall(r"[\w.+-]+@[\w.-]+\.[A-Za-z]{2,}", resume_text):
                resume_text_by_email[email.lower()] = resume_text

        for candidate in ranked:
            candidate["raw_text"] = resume_text_by_email.get(candidate["email"].lower(), "")

        # Validate emails were found
        missing = [
            candidate["name"]
            for candidate in ranked
            if candidate["email"] == "NOT_FOUND" or not candidate["raw_text"]
        ]
        if missing:
            return {
                "error": f"Could not extract email from resumes: {missing}"
            }

        return {"ranked_candidates": ranked}

    except (json.JSONDecodeError, KeyError, ValueError) as e:
        return {
            "error": f"ResumeScreener failed to parse output: {e}\nRaw: {last_message}"
        }
